name: HubSpot Pipeline
on:
  workflow_dispatch:

env:
    HUBSPOT__API_KEY: ${{ secrets.HUBSPOT__API_KEY }}
    DESTINATION__SNOWFLAKE__CREDENTIALS__HOST: ${{ secrets.DESTINATION__SNOWFLAKE__CREDENTIALS__HOST }}
    DESTINATION__SNOWFLAKE__CREDENTIALS__USERNAME: ${{ secrets.DESTINATION__SNOWFLAKE__CREDENTIALS__USERNAME }}
    DESTINATION__SNOWFLAKE__CREDENTIALS__PRIVATE_KEY: ${{ secrets.DESTINATION__SNOWFLAKE__CREDENTIALS__PRIVATE_KEY }}
    DESTINATION__SNOWFLAKE__CREDENTIALS__PRIVATE_KEY_PASSPHRASE: ${{ secrets.DESTINATION__SNOWFLAKE__CREDENTIALS__PRIVATE_KEY_PASSPHRASE }}
    DESTINATION__SNOWFLAKE__CREDENTIALS__ROLE: ${{ secrets.DESTINATION__SNOWFLAKE__CREDENTIALS__ROLE }}
    DESTINATION__SNOWFLAKE__CREDENTIALS__WAREHOUSE: ${{ secrets.DESTINATION__SNOWFLAKE__CREDENTIALS__WAREHOUSE }}
    DESTINATION__SNOWFLAKE__CREDENTIALS__DATABASE: ${{ secrets.DESTINATION__SNOWFLAKE__CREDENTIALS__DATABASE }}


jobs:
  hubspot-pipeline:
    name: HubSpot Pipeline
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.9'
          cache: 'pipenv'
      - name: Install Pipenv
        run: |
          pip3 install --user pipenv
          pipenv install
      - name: Run HubSpot Pipeline
        run: |
          echo "Running HubSpot Pipeline"
          pipenv run python hubspot_pipeline/hubspot_pipeline.py